// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Admin struct {
	ID        int32        `json:"id"`
	Email     string       `json:"email"`
	Password  string       `json:"password"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type BlogPost struct {
	ID        int32          `json:"id"`
	Title     string         `json:"title"`
	Body      string         `json:"body"`
	ImageLink sql.NullString `json:"image_link"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

type Project struct {
	ID        int32        `json:"id"`
	Name      string       `json:"name"`
	Status    string       `json:"status"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type ProjectAfter struct {
	ProjectID   int32          `json:"project_id"`
	Body        sql.NullString `json:"body"`
	ProjectCost sql.NullInt32  `json:"project_cost"`
	VideoLink   sql.NullString `json:"video_link"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type ProjectBefore struct {
	ProjectID       int32          `json:"project_id"`
	Body            string         `json:"body"`
	EstimatedTarget int32          `json:"estimated_target"`
	CurrentFunds    int32          `json:"current_funds"`
	VideoLink       sql.NullString `json:"video_link"`
	CreatedAt       sql.NullTime   `json:"created_at"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
}

type ProjectImage struct {
	ID        int32        `json:"id"`
	ProjectID int32        `json:"project_id"`
	Phase     string       `json:"phase"`
	ImageLink string       `json:"image_link"`
	CreatedAt sql.NullTime `json:"created_at"`
}
