// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.865
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ComingSoon() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!-- ==== coming soon section start ==== --> <section class=\"soon\"><div class=\"container\"><div class=\"row\"><div class=\"col-12\"><div class=\"soon__inner\"><div class=\"soon__logo\"><a href=\"index.html\"><img src=\"/static/images/logo-light.png\" alt=\"Image\"></a></div><div class=\"countdown-wrapper\"><div class=\"clock\"><div class=\"hand hour-hand\"></div><div class=\"hand minute-hand\"></div><div class=\"hand second-hand\"></div><div class=\"center-dot\"></div><div class=\"center-dot-orange\"></div><div class=\"hour-markers\"></div><div class=\"minute-markers\"></div></div><div class=\"time-countdown\"><div class=\"counter-column\"><span class=\"count day\">0</span>Days</div><div class=\"counter-column\"><span class=\"count hour\">0</span>Hours</div><div class=\"counter-column\"><span class=\"count minute\">0</span>Minutes</div><div class=\"counter-column\"><span class=\"count second\">0</span>Seconds</div></div></div><div class=\"content\"><h4 class=\"title-animation\">Something exciting is coming!</h4><p>Exciting updates are on the way.</p><p>Stay with us!</p><form method=\"post\" action=\"#\"><div class=\"form-group\"><input type=\"email\" name=\"sub-email\" id=\"subEmail\" placeholder=\"Your Email\" required> <button type=\"submit\" class=\"btn--primary\" aria-label=\"subscribe our newsletter\" title=\"subscribe our newsletter\">Subscribe</button></div></form></div></div></div></div></div><div class=\"soon-bg\"><img src=\"/static/images/banner/banner-one-bg.png\" alt=\"Image\" class=\"parallax-image\"></div></section>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Base("Coming Soon").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
