// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Donate() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"confirmation-form\" class=\"container mt-5\"><h2 class=\"text-center mb-4\">Confirm Your Donation</h2><p class=\"text-center\">Please fill out this form so we can confirm your transfer and send a receipt.</p><form><div class=\"mb-3\"><label for=\"donor-name\" class=\"form-label\">Full Name</label> <input type=\"text\" class=\"form-control\" id=\"donor-name\" placeholder=\"John Doe\" required></div><div class=\"mb-3\"><label for=\"amount-donated\" class=\"form-label\">Amount Donated</label> <input type=\"number\" class=\"form-control\" id=\"amount-donated\" placeholder=\"e.g., 5000\" required></div><div class=\"mb-3\"><label for=\"project-choice\" class=\"form-label\">Choose the Project</label> <select class=\"form-select\" id=\"project-choice\" required><option selected disabled value=\"\">Select a project...</option> <option value=\"project1\">Project 1: Clean Water Initiative</option> <option value=\"project2\">Project 2: Educational Outreach</option></select></div><div class=\"mb-3\"><label for=\"phone-number\" class=\"form-label\">Phone Number</label> <input type=\"tel\" class=\"form-control\" id=\"phone-number\" placeholder=\"e.g., 0801 234 5678\" required></div><button type=\"submit\" class=\"btn btn-primary w-100 btn-lg\" id=\"confirm_btn\">Submit</button></form></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Base("").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
